services:
  slooze-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slooze
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  slooze-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@slooze-db:5432/slooze?schema=public"
      JWT_SECRET: "supersecretkey"
    depends_on:
      - slooze-db

  slooze-frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_GRAPHQL_API: "http://localhost:3000/graphql"
    depends_on:
      - slooze-backend

volumes:
  postgres_data:
